# Generated by Django 6.0.2 on 2026-02-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_hostel_hostel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
