# Generated by Django 6.0.2 on 2026-02-06 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_booking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='student',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='management.student'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.CharField(default=True),
        ),
    ]
