# Generated by Django 6.0.2 on 2026-02-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_hostel_student_alter_booking_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='student',
        ),
        migrations.AddField(
            model_name='hostel',
            name='location',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='performance',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
