# Generated by Django 6.0.2 on 2026-02-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='Comments',
        ),
    ]
