# Generated by Django 6.0.2 on 2026-03-04 00:00

import django.db.models.deletion
from django.db import migrations, models


def dedupe_bookings_before_unique_constraints(apps, schema_editor):
    Booking = apps.get_model('management', 'Booking')
    Hostel = apps.get_model('management', 'Hostel')

    # Keep one booking per student and one booking per room.
    # Priority: newest booking (higher booking_date, then higher id).
    seen_students = set()
    seen_rooms = set()
    bookings_to_delete = []

    ordered_bookings = Booking.objects.all().order_by('-booking_date', '-id')
    for booking in ordered_bookings:
        if booking.name_id in seen_students or booking.room_id in seen_rooms:
            bookings_to_delete.append(booking.id)
            continue

        seen_students.add(booking.name_id)
        seen_rooms.add(booking.room_id)

    if bookings_to_delete:
        Booking.objects.filter(id__in=bookings_to_delete).delete()

    # Sync room availability with bookings kept after cleanup.
    Hostel.objects.all().update(is_available=True)
    if seen_rooms:
        Hostel.objects.filter(id__in=seen_rooms).update(is_available=False)


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_hostel_owner_user_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(
                choices=[('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')],
                default='pending_payment',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            dedupe_bookings_before_unique_constraints,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('name',), name='one_booking_per_student'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('room',), name='one_booking_per_room'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_code', models.CharField(max_length=100)),
                ('paid_by_phone', models.CharField(max_length=20)),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                (
                    'booking',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payment',
                        to='management.booking',
                    ),
                ),
            ],
        ),
    ]
